version: '3.8'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:${APP_VERSION}
    container_name: ${APP_CONTAINER_NAME}
    volumes:
      - logstash:/opt/logstash
    restart: always

networks:
  default:
    name: ${APP_NETWORK}
    external: true

volumes:
  logstash:
